repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --py37-plus
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]

      - id: black
        name: black
        entry: black
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]

      - id: mypy
        name: mypy
        entry: bash -c 'cd pytorch; mypy .'
        language: python
        types: [python]
        require_serial: true

      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]

      - id: pytest
        name: pytest
        entry: bash -c 'cd pytorch; pytest --durations=0 unit_test'
        language: python
        types: [python]
        always_run: true
        pass_filenames: false
        verbose: true
