repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --py38-plus
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]

      - id: black
        name: black
        entry: black -C
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true

      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]

      - id: pytest
        name: pytest
        entry: pytest --cov=src --cov-report=html --durations=0
        language: python
        types: [python]
        always_run: true
        pass_filenames: false
        verbose: true
