language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install --upgrade pytest
  - pip install pytest-cov codecov
script:
  - pytest -s --cov=src --cov-report= --durations=0 -k "not test_one_epoch"
after_success:
  - codecov
