#!/usr/bin/env bash

# If any command inside script returns error, exit and return that error
set -e

# Ensure that we're always inside the root of our application,
# no matter which directory we run script: Run `./scripts/run-tests`
cd "${0%/*}/.."
cd "pytorch"

# Type Checking
mypy .

# Auto-code formatters
isort .
black . --exclude pytorch/data
git add .

# Style Checking
flake8 .
find . -iname "*.py" | xargs pylint

# Testing
pytest -s