name: Python package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
    - name: mypy
      run: |
        uv run mypy --install-types --non-interactive .
    - name: pytest
      if: always()
      run: |
        uv run pytest --cov=ai_toolkit --cov-report= --durations=0 -k "not test_one_epoch"
    - name: codecov
      uses: codecov/codecov-action@v5
